ci: Use deploy time download url instead of cloudFlare worker

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,6 +40,19 @@ jobs:
             echo -e "User-agent: *\nDisallow: /" > public/robots.txt
           fi
 
+      - name: Fetch and Update Download Link
+        run: |
+          MANAGER_PROPS_URL="https://raw.githubusercontent.com/HundEdFeteTree/HappyFunTest/refs/heads/main/gradle.properties"
+          VERSION=$(curl -s $MANAGER_PROPS_URL | grep -m 1 "^\s*version\s*=" | cut -d "=" -f 2 | tr -d '[:space:]')
+          if [ -z "$VERSION" ]; then
+            echo "Error: Could not find version string in gradle.properties." >&2
+            exit 1
+          fi
+          DOWNLOAD_URL="https://github.com/MorpheApp/morphe-manager/releases/download/v$VERSION/morphe-manager-$VERSION.apk"
+          sed -i "s|^/download.*|/download    $DOWNLOAD_URL    302|g" public/_redirects
+          echo "Updated _redirects file:"
+          cat public/_redirects
+
       - name: Install Wrangler
         run: npm install -g wrangler
 
